ecommerce:
    resource: "@EcommerceBundle/Controller/"
    type:     annotation
    prefix:   /

utilisateurs:
    resource: "@UtilisateursBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    
# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

utilisateurs_homepage:
    path:     /
    defaults: { _controller: UtilisateursBundle:Default:index }
